# 100 numpy exercises (Optional)

Source: https://github.com/rougier/numpy-100


#### How to run this notebook

The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.

#### How to get help

If you are stuck, you can ask for help on the community forum: https://jovian.ml/forum/t/100-numpy-exercises-hints-discussions-help/10561 . You can get help with errors, ask for hints, and share your solutions with others.

If you're new to Numpy, check out this notebook for a quick tutorial: https://jovian.ml/aakashns/python-numerical-computing-with-numpy


#### Saving your work

Remember to save a snapshot of your work from time to time using to your Jovian.ml account.

In [1]:
!pip install jovian --upgrade --quiet

In [2]:
import jovian

<IPython.core.display.Javascript object>

In [6]:
jovian.commit(filename='100-numpy-exercises.ipynb', project='100-numpy-exercises')

<IPython.core.display.Javascript object>

[jovian] Creating a new project "lancelot-gohqk/100-numpy-exercises"
[jovian] Committed successfully! https://jovian.ai/lancelot-gohqk/100-numpy-exercises


'https://jovian.ai/lancelot-gohqk/100-numpy-exercises'

`jovian.commit` uploads the notebook to your Jovian.ml account, captures the Python environment and creates a shareable link for your notebook as shown above. You can use this link to share your work and let anyone (including you) run your notebooks and reproduce your work. Learn more: https://jovian.ml/docs/


In [4]:
# Ucomment the next line if you need install numpy
# !pip install numpy --upgrade

#### 1. Import the numpy package under the name `np` (★☆☆)

In [11]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [19]:
print("The numpy version is " + np.__version__ + "\n") 
print(np.show_config())

The numpy version is 1.20.3

blas_info:
    libraries = ['cblas', 'blas', 'cblas', 'blas']
    library_dirs = ['/opt/conda/lib']
    include_dirs = ['/opt/conda/include']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    define_macros = [('NO_ATLAS_INFO', 1), ('HAVE_CBLAS', None)]
    libraries = ['cblas', 'blas', 'cblas', 'blas']
    library_dirs = ['/opt/conda/lib']
    include_dirs = ['/opt/conda/include']
    language = c
lapack_info:
    libraries = ['lapack', 'blas', 'lapack', 'blas']
    library_dirs = ['/opt/conda/lib']
    language = f77
lapack_opt_info:
    libraries = ['lapack', 'blas', 'lapack', 'blas', 'cblas', 'blas', 'cblas', 'blas']
    library_dirs = ['/opt/conda/lib']
    language = c
    define_macros = [('NO_ATLAS_INFO', 1), ('HAVE_CBLAS', None)]
    include_dirs = ['/opt/conda/include']
None


#### 3. Create a null vector of size 10 (★☆☆)

In [34]:
array1 = np.zeros([10])

#### 4. How to find the memory size of any array (★☆☆)

In [35]:
#get the size of the array multiply by the memory size of one element in the array
mem_size = array1.size * array1.itemsize 
print(f"The memory size of the array is: {mem_size} bytes")

The memory size of the array is: 80 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [38]:
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [40]:
array2 = np.zeros([10])
array2[4] = 1
array2

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [42]:
array3 = np.arange(10,50)
array3

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [45]:
np.flip(array3)

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [49]:
array4 = np.arange(0,9).reshape(3,3)
array4

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [52]:
array5 = np.array([1,2,0,0,4,0])
np.nonzero(array5)

(array([0, 1, 4]),)

Save your progress by commiting your work to Jovian

In [53]:
import jovian

In [54]:
jovian.commit(project='numpy-100-exercises')

<IPython.core.display.Javascript object>

[jovian] Creating a new project "lancelot-gohqk/numpy-100-exercises"
[jovian] Committed successfully! https://jovian.ai/lancelot-gohqk/numpy-100-exercises


'https://jovian.ai/lancelot-gohqk/numpy-100-exercises'

#### 11. Create a 3x3 identity matrix (★☆☆)

In [55]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [58]:
array6 = np.random.randn(3,3,3)
array6

array([[[ 0.6488244 ,  0.37479576,  0.40550147],
        [ 1.15457886,  1.09166182,  0.63643033],
        [ 0.05696349,  0.58007647, -1.03339755]],

       [[ 0.65927421, -1.52724491, -2.08450346],
        [ 1.01723905, -0.14040856,  0.10236268],
        [ 1.26146934, -0.17422773, -0.25982511]],

       [[-1.00127765, -1.31282921,  1.15511146],
        [ 0.65802987,  1.4448431 , -0.47462523],
        [-0.11213488,  1.6381554 , -0.08808332]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [68]:
array7 = np.random.randn(10,10)
print(array7)
print(f'The minimum value is {array7.min()}')
print(f'The maximum value is {array7.max()}')

[[-0.41041328 -0.79024896 -0.19118783 -1.0769618   0.63374034 -0.97038832
   1.23652482  1.13078596 -0.74656854 -0.30775326]
 [-0.617174    1.28302658 -0.48123954  0.96880723  0.46338111  0.68856366
   0.27171886  0.66087471 -2.27037233  1.18263139]
 [-0.09333588  0.3583906  -1.30406672 -1.27092404  0.85316398 -0.01890002
  -0.84507506 -1.62720764  0.05009799  0.55167534]
 [-1.57468161  0.08579918 -0.7935177   0.37254523  0.18498148  0.56571454
   0.73070695  0.62971228 -0.51239384 -0.16326704]
 [-1.3443155   0.46992599 -0.03474521  0.12415854  1.12540151  1.22688479
   0.28906601  1.42263654 -0.27169036  0.34743427]
 [ 0.27639982 -1.73156758 -0.04491677  0.32100286 -0.79281965 -1.3135593
  -0.70867317  1.17823271 -1.30143285  0.14736278]
 [ 1.50028671  1.39295258 -1.82478657 -1.42047748  0.59466818 -0.15416703
   1.40450557 -0.95973866 -0.91246549 -0.05215881]
 [-0.91547877  0.86217633  0.31805815  1.6727174   1.83559055  0.33354951
  -1.43715593 -0.16313479  1.20779787  0.1224131 ]
 

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [71]:
array8 = np.random.randn(30)
print(array8)
print(f'The mean of the array is {array8.mean()}')

[-1.18784956  0.24208315 -0.27307756  0.58421638 -1.11416526  0.2795335
 -1.39176916  0.38948091 -1.63078599  0.62032095  0.20599971 -1.17358601
  0.70303524 -1.34068017  0.67024958  1.09576172 -0.36649614 -0.75744272
 -0.98777172 -0.54252165  0.26348579 -0.37465653  0.75829465  0.58836686
  0.64340378  0.21294244 -2.28451132 -0.4284265   0.64159681 -1.18664124]
The mean of the array is -0.23805366848467235


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [85]:
array9 = np.ones([10,10])
array9[1:-1,1:-1] = 0
print(array9)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [96]:
array10 = np.ones([10,10]) 
array10 = np.pad(array10, pad_width=1, mode='constant', constant_values=0)
print(array10)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [98]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [104]:
array11 = np.diag(np.arange(4)+1, k=-1)
array11

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [110]:
array12 = np.zeros([8,8])
array12[::2,1::2] = 1
array12[1::2,::2] = 1
array12

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [120]:
np.unravel_index(99, [6,7,8])

(1, 5, 3)

Save your progress by commiting your work to Jovian

In [121]:
import jovian

In [122]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "lancelot-gohqk/numpy-100-exercises" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/lancelot-gohqk/numpy-100-exercises


'https://jovian.ai/lancelot-gohqk/numpy-100-exercises'

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [129]:
array13 = np.array([[1,0],[0,1]])
array13 = np.tile(array13,(4,4))
array13

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [141]:
# formula = (array - array.min) divide by (array.max - array.min) = (a - a.min) / (a.max - a.min)
arr14 = np.random.randn(5,5)
print('This is the original matrix:\n\n', arr14)
arr14 = (arr14 - arr14.min()) / (arr14.max() - arr14.min())
print('\nThis is the normalised matrix:\n\n', arr14)

This is the original matrix:

 [[-1.26516724 -1.26558542  1.43864251  1.03931393 -0.13902183]
 [ 0.17610094  1.32679709  1.2539469  -0.37997466  0.40415093]
 [-0.44352188  1.49807088  0.154597    0.77608089  0.80626061]
 [-0.40877951  1.54277267  0.19090365  0.6093849   0.61237627]
 [ 1.77580061  0.51562369 -0.01838269 -0.18677209 -1.3318231 ]]

This is the normalised matrix:

 [[0.02144914 0.02131457 0.89150614 0.76300648 0.38383066]
 [0.48523379 0.85551548 0.83207307 0.30629462 0.55861784]
 [0.28584581 0.91062955 0.47831405 0.67830091 0.68801242]
 [0.29702553 0.92501411 0.48999715 0.62465993 0.62562252]
 [1.         0.59448857 0.42265104 0.36846514 0.        ]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [15]:
color = np.dtype([('r',np.ubyte), ('g',np.ubyte),('b',np.ubyte),('a',np.ubyte)])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [18]:
arrX = np.random.rand(5,3)
print(arrX)
arrY = np.random.rand(3,2)
print(arrY)
arrZ = arrX @ arrY
arrZ

[[0.54806115 0.63351952 0.70433852]
 [0.93647721 0.67753895 0.8617163 ]
 [0.91409842 0.39007353 0.36602476]
 [0.54831433 0.8214007  0.77534324]
 [0.73987528 0.87180923 0.01556449]]
[[0.03486014 0.41350598]
 [0.45413251 0.62407191]
 [0.8755957  0.94340188]]


array([[0.92352308, 1.28646258],
       [1.09485329, 1.62301673],
       [0.52950037, 0.96672753],
       [1.07102629, 1.47080463],
       [0.43533727, 0.86469807]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [22]:
arr1 = np.arange(15)
arr1[(arr1 >= 3) & (arr1 <= 8)] *= -1
arr1

array([ 0,  1,  2, -3, -4, -5, -6, -7, -8,  9, 10, 11, 12, 13, 14])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [23]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [24]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/tmp/ipykernel_35/3912170336.py:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
/tmp/ipykernel_35/3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


#### 29. How to round away from zero a float array ? (★☆☆)

In [37]:
x = np.random.rand(10)
print(x)
print(np.round(x,0))

[0.19599921 0.80090106 0.14011011 0.34237388 0.8673815  0.09484106
 0.02944741 0.83242271 0.25944433 0.24597936]
[0. 1. 0. 0. 1. 0. 0. 1. 0. 0.]


#### 30. How to find common values between two arrays? (★☆☆)

In [49]:
x1 = np.random.randint(0,10,20)
print(x1)
x2 = np.random.randint(0,10,20)
print(x2)
x3 = np.intersect1d(x1,x2)
print(x3)

[5 8 7 0 0 0 9 0 6 8 5 8 1 8 4 0 6 6 7 1]
[8 9 9 2 0 3 0 9 9 0 1 5 6 2 7 2 9 1 3 3]
[0 1 5 6 7 8 9]


Save your progress by commiting your work to Jovian

In [47]:
import jovian

In [48]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "lancelot-gohqk/numpy-100-exercises" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/lancelot-gohqk/numpy-100-exercises


'https://jovian.ai/lancelot-gohqk/numpy-100-exercises'

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [51]:
np.seterr(all="ignore")

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [52]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [53]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')

print(yesterday, today, tomorrow)

2022-06-18 2022-06-19 2022-06-20


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [54]:
july2016 = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(july2016)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [55]:
A = -10
B = 20
z = ((A+B)*(-A/2))
print(z)

B = np.add(A,B)
A = np.divide(A,2)
A = np.negative(A)
A = np.multiply(A,B)
print(A)

50.0
50.0


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [56]:
Z = np.random.uniform(0,10,10)

print (Z - Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))
print (np.trunc(Z))

[1. 6. 6. 4. 4. 1. 5. 4. 4. 0.]
[1. 6. 6. 4. 4. 1. 5. 4. 4. 0.]
[1. 6. 6. 4. 4. 1. 5. 4. 4. 0.]
[1 6 6 4 4 1 5 4 4 0]
[1. 6. 6. 4. 4. 1. 5. 4. 4. 0.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [63]:
arr = np.zeros([5,5])
print(arr)
arr += np.arange(5)
print(f'\n\n{arr}')

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [65]:
def generate():
   for n in range(10):
       yield n
newArr = np.fromiter(generate(),dtype=float,count=-1)
print("New array:")
print(newArr)

New array:
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [68]:
vect = np.linspace(0,1,11,endpoint=False)[1:]
print(vect)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [75]:
vect = np.random.randint(0,1000,10)
print(vect)
vect = np.sort(vect)
print(f'\n{vect}')

[272 138 590 315 520 101 723 108 751 608]

[101 108 138 272 315 520 590 608 723 751]


Save your progress by commiting your work to Jovian

In [7]:
import jovian

In [61]:
jovian.commit(filename='100-numpy-exercises.ipynb')

<IPython.core.display.Javascript object>

[jovian] Updating notebook "lancelot-gohqk/100-numpy-exercises" on https://jovian.ai/
[jovian] Committed successfully! https://jovian.ai/lancelot-gohqk/100-numpy-exercises


'https://jovian.ai/lancelot-gohqk/100-numpy-exercises'

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [15]:
arr1 = np.random.randint(0,100,20)
print(arr1)
print(np.add.reduce(arr1))

[11 36 39 40  4 64  7 96 73 80 75 94 20 39 22 83 81 59 58 99]
1080


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [36]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

# Assuming identical shape of the arrays and a tolerance for the comparison of values(very small tolerance)
equal = np.allclose(A,B)
print(A,B)
print(equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(A,B)
print(equal)

[0 1 1 0 1] [1 0 1 1 1]
False
[0 1 1 0 1] [1 0 1 1 1]
False


#### 43. Make an array immutable (read-only) (★★☆)

In [41]:
arr1 = np.ones([10,10])
print(arr1)
arr1.flags.writeable=False

arr1[2] = 0

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [49]:
z= np.random.rand(10,2)
x,y = z[:,0], z[:,1]
r = np.sqrt(x**2+y**2)
t = np.arctan2(y,x)
print(z)
print(r)
print(t)

[[0.24432012 0.72972819]
 [0.16435528 0.93558589]
 [0.16970847 0.07495447]
 [0.72725679 0.51683819]
 [0.19846462 0.60443549]
 [0.57959751 0.0290436 ]
 [0.14550442 0.35071795]
 [0.55526476 0.52680709]
 [0.24637784 0.82629888]
 [0.10372747 0.2282705 ]]
[0.76954243 0.94991242 0.18552396 0.89220186 0.6361843  0.58032474
 0.37970333 0.7654049  0.86224816 0.25073255]
[1.24771758 1.3968997  0.41590186 0.61784993 1.25354011 0.05006807
 1.17753205 0.75910498 1.28101894 1.14428447]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [60]:
Z = np.random.uniform(0.0,100,10)
print(Z)
print(f'\nThe max is at index Z[{Z.argmax()}] with the value {Z[Z.argmax()]}\n')
Z[Z.argmax()] = 0
print(Z)

[ 0.10551057 11.68499238 96.54581945 74.09652628 65.99668211 92.13742615
  8.95166408 42.38109946 85.8552569  12.6868028 ]

The max is at index Z[2] with the value 96.54581944843223

[ 0.10551057 11.68499238  0.         74.09652628 65.99668211 92.13742615
  8.95166408 42.38109946 85.8552569  12.6868028 ]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [65]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5), np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [83]:
X = np.arange(6)
Y = X + 0.5
print(X)
print(Y)
C = 1.0 / np.subtract.outer(X, Y)
print(f'\nOutput of C:\n{C}\n')
print(np.linalg.det(C))

[0 1 2 3 4 5]
[0.5 1.5 2.5 3.5 4.5 5.5]

Output of C:
[[-2.         -0.66666667 -0.4        -0.28571429 -0.22222222 -0.18181818]
 [ 2.         -2.         -0.66666667 -0.4        -0.28571429 -0.22222222]
 [ 0.66666667  2.         -2.         -0.66666667 -0.4        -0.28571429]
 [ 0.4         0.66666667  2.         -2.         -0.66666667 -0.4       ]
 [ 0.28571429  0.4         0.66666667  2.         -2.         -0.66666667]
 [ 0.22222222  0.28571429  0.4         0.66666667  2.         -2.        ]]

396.0368295558234


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [88]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [92]:
np.set_printoptions(threshold=float("inf"))
Z = np.random.uniform(0.0,10000.0,100).reshape(20,5)
print(Z)

[[5013.8449535  4013.80954023  655.15750042 1670.96021225 1848.4498007 ]
 [7808.19933219 6052.13160935 9672.466666   5526.94637784 2683.11148485]
 [4000.05925557 9830.0825473  3079.63819062 9899.32579175 2691.70597651]
 [ 484.98324709 8511.01823597 1081.5412772  8186.62557715 3931.30608187]
 [4407.37613918 4639.91103037 5350.791422   1030.16200716   39.23450367]
 [ 334.50387144 4209.03416669  206.77706586 5683.15410216 3105.55254958]
 [ 434.79554749 5833.84110594 3106.4077273  8850.19706181 2246.20884359]
 [4233.40876753  285.36426636 1089.64040314  878.2724816  6496.96095481]
 [9051.89462787 2053.70051731 6197.72582795 1630.36376579 6857.98359835]
 [ 580.63906687 8740.37961727 7748.20678593 4079.96726606 6766.10857938]
 [ 269.57298555 5139.53662465 5348.60314777 8252.84503768 3370.72194626]
 [8074.38924449 4296.25391326 6948.25035002 4403.75152994 6098.94134219]
 [1899.97736284 5836.97089371   20.97095051 5832.85367793 9448.72464325]
 [3152.93828697 5088.57357248 2097.3589539  2331.37

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [95]:
Z = np.arange(100)
v = np.random.uniform(0,100)
print(v)
index = (np.abs(Z-v)).argmin()
print(Z[index])

26.128737747246856
26


Save and commit your work.

In [96]:
import jovian

In [97]:
jovian.commit(filename='100-numpy-exercises')

<IPython.core.display.Javascript object>

[jovian] Updating notebook "lancelot-gohqk/100-numpy-exercises" on https://jovian.ai/
[jovian] Committed successfully! https://jovian.ai/lancelot-gohqk/100-numpy-exercises


'https://jovian.ai/lancelot-gohqk/100-numpy-exercises'

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

Save and commit your work.

In [ ]:
import jovian

In [ ]:
jovian.commit()

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

Save and commit your work

In [ ]:
import jovian

In [ ]:
jovian.commit()

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

Save and commit your work.

In [ ]:
import jovian

In [ ]:
jovian.commit()

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

Save and commit your work

In [ ]:
import jovian

In [ ]:
jovian.commit()

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

Save and commit your work

In [ ]:
import jovian

In [ ]:
jovian.commit()

Congratulations on completing the 100 exercises, well done!

#### What to do next?

- Share your completed notebook on Facebook, LinkedIn or Twitter and challenge your friends.
- Share your solutions and help others on the forum: https://jovian.ml/forum/t/100-numpy-exercises-hints-discussions-help/10561
- Check out our course on "Data Analysis with Python: Zero to Pandas" - https://jovian.ml/learn/data-analysis-with-python-zero-to-pandas
- Star this repository to show your appreciation for the original author of this notebook: https://github.com/rougier/numpy-100